### ISSUE TITLE
TypeError: Cannot read property 'generate' of undefined

### ISSUE THREAD

**Issue by brianshano** [intercom/ember-href-to#94]
Ember 2.9.0

Running ember test with ember-href-to v1.14.0 is fine. 
Using v1.15.0 we get some failing integration tests:

```
        actual: >
            null
        stack: >
            TypeError: Cannot read property 'generate' of undefined
                at Class.generate (http://localhost:7357/assets/vendor.js:49196:42)
                at Class.urlFor (http://localhost:7357/assets/vendor.js:76358:48)
                at hrefTo (http://localhost:7357/assets/vendor.js:144238:26)
                at Class.compute (http://localhost:7357/assets/vendor.js:144251:23)
                at Child.compute (http://localhost:7357/assets/vendor.js:34567:26)
                at Child.value (http://localhost:7357/assets/vendor.js:34897:27)
                at read (http://localhost:7357/assets/vendor.js:35290:21)
                at Object.readArray (http://localhost:7357/assets/vendor.js:35312:16)
                at Child.compute (http://localhost:7357/assets/vendor.js:34434:48)
                at Child.value (http://localhost:7357/assets/vendor.js:34897:27)
        message: >
            Died on test #1     at Module.callback (http://localhost:7357/assets/tests.js:27187:24)
                at Module.exports (http://localhost:7357/assets/vendor.js:115:32)
                at requireModule (http://localhost:7357/assets/vendor.js:36:18)
                at TestLoader.<anonymous> (http://localhost:7357/assets/test-support.js:7700:11)
                at TestLoader.require (http://localhost:7357/assets/test-support.js:7690:27)
                at TestLoader.loadModules (http://localhost:7357/assets/test-support.js:7682:16)
                at Function.load (http://localhost:7357/assets/test-support.js:7633:26): Cannot read property 'generate' of undefined
        Log: |
```

The test renders a component that contains a href-to call:

<a href="{{href-to 'routeName'}}"></a>

**Comment by mazondo** [comment]
This is happening to us as well, dropping to 1.14 resolved it

**Comment by GavinJoyce** [comment]
@mazondo what version of ember are you using?

**Comment by nadnoslen** [comment]
I just bumped into this in my unit tests (works fine in the app).

Essentially I have a component rendering a handful of links using `href-to`.

Ember-2.9.1
ember-href-to-1.15.1

Just noticed that @mazondo downgraded ember-href-to-1.14; I'll try that.

**Comment by nadnoslen** [comment]
So downgrading to ember-href-to-1.14.0 worked for me too.  Thanks @mazondo

**Comment by cmgurba** [comment]
Errors exist in Ember-2.16.2 as well.
Confirmed downgrading to ember-href-to-1.14.0 does get rid of the errors here as well.

**Comment by GCheung55** [comment]
I'm not exactly sure who to ping, so I'm going to try @rwjblue. It seems that 'router' is not being included when imported in `ember-routing/system/router`. I'm seeing this with `ember@2.17.1`.

**Comment by GCheung55** [comment]
I was seeing this on 1.15.x with ember@2.17.1. Looking into this some it looks like the router isn't setup yet, that's why `this._routerMicrolib` is undefined.

`this._routerMicrolib` is setup in the `_initRouterJs` method. My guess is that the router isn't setup in component tests.

**Comment by GCheung55** [comment]
Looking around some more, it looks like the [integration test](https://github.com/intercom/ember-href-to/blob/master/tests/integration/href-to-test.js) is setting up the router with:

```javascript
beforeEach() {
  getOwner(this).lookup('router:main').setupRouter();
}
```

@GavinJoyce Is there a way to automatically setup the router without needing to manually add a beforeEach to every integration test?

**Comment by panthony** [comment]
@GCheung55 Adding this did fix this particular issue but it broke lot's of other tests.

Looks like this call has side-effects that impact other tests.

**Comment by GCheung55** [comment]
@panthony I see. My project has a couple of components that use `href-to` so setting up the router in a `beforeEach` for their respective tests addressed the issue but I didn’t see side effects to other tests.

We’re the side-effect errors you saw consistent?

**Comment by panthony** [comment]
@GCheung55 Typically I have:

In integration tests:

> Source: | Error: Must setup rendering context before attempting to interact with elements.

In route tests:

> Error: Assertion Failed: Attempting to inject an unknown injection: 'service:i18n'

If I add `service:i18n` in `needs` array it will fails eventually with:

> Error: Property set failed: object in path "session" could not be found or was destroyed.

Maybe this is due to `ember-simple-auth` somehow.

I did not try to fix them really. I do not wish to add something in a test that break another one, `setupRouter` do something that lives beyond the test.

**Comment by erichonkanen** [comment]
+1 just ran into this when using `<a href={{href-to foo}}` in integration test, going to downgrade for now

**Comment by chbonser** [comment]
Just in case this data point is helpful... I'm using Ember 3.3.1 and both 1.14.0 and 1.15.1 cause the error.

**Comment by erichonkanen** [comment]
are we going to get a new release with this? I'm getting `Uncaught TypeError: Cannot read property 'generate' of undefined` in 1.15.1 AND 1.14.0 using latest ember 3.4.1

**Comment by patocallaghan** [comment]
The ember-href-to package is now maintained by the Ember community and lives at https://github.com/adopted-ember-addons/ember-href-to. We're closing this issue and archiving this repo. If you still think it's relevant, please reopen it against the new repo.
